### PR TITLE
Added SPI Port select

### PR DESCRIPTION
**Pull request by lewisxhe**
| Q               | A
| -------------   | ---
| Bug fix?        | yes/no
| New feature?    | yes/no
| Doc update?     | yes/no 
| BC breaks?      | yes/no 
| Deprecations?   | yes/no
| Relative Issues | #

### CODE REVIEW

**Comment by Sonic0** [comment]
Hi @lewisxhe,
Thank you very much for this pull request. Can you give us some details on why these changes are required and on which hardware you have tested them?

**Comment by lewisxhe** [comment]
Hi , @Sonic0 
We use the DW1000 expansion module on our TWatch, our display uses VSPI, and we need to use HSPI in the arduino-dw1000-ng, so I have expanded to choose SPI as the method of use. I have tested it on our board! For specific code, please refer to
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/commit/3e80659bde3edc8f5106a7758f3c6b596626e578

**Comment by Sonic0** [comment]
Oh wow, very interesting project. Thanks, I'm going to try this code as soon as possible.

**Comment by lewisxhe** [comment]
Hi,  @Sonic0    
Are you willing to help us improve our products? We are willing to send you two free samples to help us improve. If you are willing, please send your address to jiangcuifeng@lilygo.cc, thanks.

**Comment by Sonic0** [comment]
Hi @lewisxhe, I have no time to help the community. It's already hard to respond to issues and pull-requests on this project.

**Comment by lewisxhe** [comment]
okay then ! If you need, we can send you two boards!

**Comment by Sonic0** [comment]
The code works well on ESP8266 and Arduino pro mini 3,3V. I haven't other hardware to test. @0nism what do you think about it?

**Comment by anacromaniac** [comment]
I like it!

**Comment by Sonic0** [comment]
Thank you very much for your contribution @lewisxhe!

**Pull request merged**
