### PR TITLE
Added EEPROM option for saving the antenna delay

### PR DESCRIPTION
**Pull request by Bartvelp**
| Q               | A
| -------------   | ---
| Bug fix?        | no
| New feature?    | yes
| Doc update?     |no 
| BC breaks?      | no 
| Deprecations?   | no
| Relative Issues | #62 

I added some methods to save anttenna delay in the EEPROM, some sample code:
```cpp
  uint16_t randNumber = random(300);
  Serial.println("Now in EEPROM: " + String(DW1000Ng::getSavedAntennaDelay()));
  Serial.println("TX delay: " + String(DW1000Ng::getTxAntennaDelay()));
  Serial.println("RX delay: " + String(DW1000Ng::getRxAntennaDelay()));
  DW1000Ng::setAntennaDelayFromEEPROM();
  Serial.println("Restored from EEPROM");
  Serial.println("TX delay: " + String(DW1000Ng::getTxAntennaDelay()));
  Serial.println("RX delay: " + String(DW1000Ng::getRxAntennaDelay()));
  Serial.println("Got random num: " + String(randNumber));
  Serial.println("Saving");
  DW1000Ng::setAndSaveAntennaDelay(randNumber);
  Serial.println("Now in EEPROM: " + String(DW1000Ng::getSavedAntennaDelay()));
  Serial.println("TX delay: " + String(DW1000Ng::getTxAntennaDelay()));
  Serial.println("RX delay: " + String(DW1000Ng::getRxAntennaDelay()));
  Serial.println("------------------------------------------");
```

Gives the following output:
```
15:18:37.582 -> Now in EEPROM: 177
15:18:37.582 -> TX delay: 0
15:18:37.582 -> RX delay: 0
15:18:37.627 -> Restored from EEPROM
15:18:37.627 -> TX delay: 177
15:18:37.672 -> RX delay: 177
15:18:37.672 -> Got random num: 219
15:18:37.672 -> Saving
15:18:37.717 -> Now in EEPROM: 219
15:18:37.717 -> TX delay: 219
15:18:37.717 -> RX delay: 219
15:18:37.762 -> ------------------------------------------
```

Hope this is what was needed, please comment if this is incorrect.

### CODE REVIEW

**Comment by Sonic0** [comment]
Hi @Bartvelp, thanks for this pull request, it's very useful. 
I think there is a bug in this code, though. Based on your code the maximum settable antenna delay is 255. In fact, you can specify an only one-byte position, so you can only hold a value from 0 to 255. Depend on your circuit the antenna delay can be > 255. You should identify how many bytes are required (based on the antenna delay input) and then use a for loop to write the value in one or more memory locations.
The most complex part of the code could be for the "get" method.
Another trick to increase EEPROM life can be the use of .update() method, in case of the value (already saved into the EEPROM) is the same you had.

**Comment by Bartvelp** [comment]
Hi @Sonic0 
Thanks for your interest, I am trying to participate a bit in the hacktoberfest. But I am afraid you've mistaken `EEPROM.put()` for `EEPROM.write()`
This `.put` method can be used a lot more freely and is not constrained to 1 byte values, [see the docs here](https://www.arduino.cc/en/Tutorial/LibraryExamples/EEPROMPut).
It also already uses `.update()` internally so the EEPROM life should be fine if you call it a lot with the same value

Here is some output from values > 255.
Code:
```cpp
  uint16_t randNumber = random(65535);
  Serial.println("Now in EEPROM: " + String(DW1000Ng::getSavedAntennaDelay()));
  Serial.println("TX delay: " + String(DW1000Ng::getTxAntennaDelay()));
  Serial.println("RX delay: " + String(DW1000Ng::getRxAntennaDelay()));
  DW1000Ng::setAntennaDelayFromEEPROM();
  Serial.println("Restored from EEPROM");
  Serial.println("TX delay: " + String(DW1000Ng::getTxAntennaDelay()));
  Serial.println("RX delay: " + String(DW1000Ng::getRxAntennaDelay()));
  Serial.println("Got random num: " + String(randNumber));
  Serial.println("Saving");
  DW1000Ng::setAndSaveAntennaDelay(randNumber);
  Serial.println("Now in EEPROM: " + String(DW1000Ng::getSavedAntennaDelay()));
  Serial.println("TX delay: " + String(DW1000Ng::getTxAntennaDelay()));
  Serial.println("RX delay: " + String(DW1000Ng::getRxAntennaDelay()));
  Serial.println("------------------------------------------");
```
Output:
```
11:47:02.346 -> Now in EEPROM: 44334
11:47:02.392 -> TX delay: 0
11:47:02.392 -> RX delay: 0
11:47:02.439 -> Restored from EEPROM
11:47:02.439 -> TX delay: 44334
11:47:02.439 -> RX delay: 44334
11:47:02.483 -> Got random num: 57788
11:47:02.483 -> Saving
11:47:02.483 -> Now in EEPROM: 57788
11:47:02.529 -> TX delay: 57788
11:47:02.529 -> RX delay: 57788
11:47:02.574 -> ------------------------------------------
```

**Comment by Sonic0** [comment]
Yes, @Bartvelp I did. Sorry for the mistake.

**Comment by anacromaniac** [comment]
Thank you for this pull request, really interesting.
I just want to point out that one piece of code could be changed from this:
```
uint16_t getSavedAntennaDelay(uint8_t eeAddress) {
		EEPROM.begin(64);
		uint16_t delay;
		EEPROM.get(eeAddress, delay);
		EEPROM.end();
		return delay;
	}

	uint16_t setAntennaDelayFromEEPROM(uint8_t eeAddress) {
		EEPROM.begin(64);
		uint16_t delay;
		EEPROM.get(eeAddress, delay);
		setAntennaDelay(delay);
		EEPROM.end();
	}
```

To this:
```
uint16_t getSavedAntennaDelay(uint8_t eeAddress) {
		EEPROM.begin(64);
		uint16_t delay;
		EEPROM.get(eeAddress, delay);
		EEPROM.end();
		return delay;
	}

	uint16_t setAntennaDelayFromEEPROM(uint8_t eeAddress) {
		uint16_t delay = getSavedAntennaDelay(eeAddress);
		setAntennaDelay(delay);
	}
```

**Comment by Bartvelp** [comment]
That is indeed more elegant, I missed it.

**Comment by Sonic0** [comment]
Thanks @0nism and @Bartvelp.
@Bartvelp, last but not least... can you make a complete Arduino example (in the examples directory) to explain to all users how to use your functions? Just basic configuration + your previous example?

**Comment by Bartvelp** [comment]
Sure, see above commit

**Pull request merged**
